restaurant/urls.py
from django.urls import path
from restaurant.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
)

app_name = "restaurant"

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/update/<int:pk>/", DishUpdateView.as_view(), name="dish-update"),
    path("dish_types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dish_types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_types/update/<int:pk>/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/update/<int:pk>/", CookUpdateView.as_view(), name="cook-update"),
]

restaurant_kitchen_servise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
]

restaurant/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        ordering = ["id"]
        verbose_name_plural = "dishes"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})

restaurant/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.views import generic
from django.urls import reverse_lazy

from restaurant.models import Cook, Dish, DishType


def index(request: HttpRequest) -> HttpResponse:
    
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()
    
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits
    }
  
    return render(request, "restaurant/index.html", context=context)


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 5
    
    
class DishDetailView(generic.DetailView):
    model = Dish
    
    
class DishCreateView(generic.CreateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-list")
    
    
class DishUpdateView(generic.UpdateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-list")
    
    
class DishTypeListView(generic.ListView):
    model = DishType
    template_name = "restaurant/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 2
    
    
class DishTypeDetailView(generic.DetailView):
    model = DishType
    context_object_name = "dish_type"
    template_name = "restaurant/dish_type_detail.html"
    paginate_by = 5
    
    
class DishTypeCreateView(generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"
    success_url = reverse_lazy("restaurant:dish-type-list")
    
    
class DishTypeUpdateView(generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"
    success_url = reverse_lazy("restaurant:dish-type-list")
    
    
class CookListView(generic.ListView):
    model = Cook
    paginate_by = 2
    
    
class CookDetailView(generic.DetailView):
    model = Cook
    
    
class CookCreateView(generic.CreateView):
    model = Cook
    fields = ("username", "first_name", "last_name", "password", "email", "years_of_experience")
    success_url = reverse_lazy("restaurant:cook-list")
    
    
class CookUpdateView(generic.UpdateView):
    model = Cook
    fields = ("username", "first_name", "last_name", "password", "email", "years_of_experience")
    success_url = reverse_lazy("restaurant:cook-list")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>Restaurant kitchen servise</title>{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     {% load static %}
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
  <body>
    {% block navbar %}
    {% include "includes/navbar.html" %}
    {% endblock%}
    {% block content %}{% endblock%}
    {% include 'includes/pagination.html' %}
    {% block pagination %}{% endblock%}
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'restaurant:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'restaurant:dish-list' %}">All dishes</a></li>
            <li><a class="dropdown-item" href="{% url 'restaurant:dish-type-list' %}">All dishe types</a></li>
            <li><a class="dropdown-item" href="{% url 'restaurant:cook-list' %}">All cooks</a></li>
            <li><hr class="dropdown-divider"></li>
          
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination pagination-lg justify-content-center pb-3 mt-5">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page=1" class="page-link shadow-lg">&laquo; first</a>
      </li>
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link shadow-lg">prev</a>
      </li>
    {% else %}
      <li class="page-item"><a class="page-link shadow-lg cursor-pointer">&laquo; first</a></li>
      <li class="page-item"><a class="page-link shadow-lg cursor-pointer">prev</a></li>
    {% endif %}

    <li class="page-item active">
      <a class="page-link shadow-lg bg-gradient-primary cursor-pointer">{{ page_obj.number }} of {{ paginator.num_pages }}</a>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link shadow-lg">next</a>
      </li>
      <li class="page-item">
        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link shadow-lg">last &raquo;</a>
      </li>
    {% else %}
      <li class="page-item"><a class="page-link shadow-lg cursor-pointer">next</a></li>
      <li class="page-item"><a class="page-link shadow-lg cursor-pointer">last &raquo;</a></li>
    {% endif %}

  </ul>
{% endif %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
  
      <h2 class="make-dish">
        {{ cook.username }}
      
      </h2>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <p class="text-dark"><strong>Email address:</strong> {{ cook.email }}</p>
        <p class="text-dark"><strong>First name:</strong> {{ cook.first_name }}</p>
        <p class="text-dark"><strong>Last name:</strong> {{ cook.last_name }}</p>
        <p class="text-dark"><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
      </div>

      <div class="border-radius-xl blur-section px-4 pt-3 pb-1">
        <h4>Dishes that the cook prepares</h4>
        <ul>
          {% for dish in cook.dishes.all %}
            <li><a class="text-gradient text-primary" href="{% url 'restaurant:dish-detail' pk=dish.id%}">{{ dish.name }}</a></li>
          {% empty %}
            <li>There are no dishes here.</li>
          {% endfor %}
        </ul>
      </div><br>

    <div class="make-dish">
      <a href="{% url 'restaurant:cook-update' cook.id %}" class="btn btn-primary btn-lg">Update profile</a><br><br>
      <a href="" class="btn btn-danger btn-lg">Delete account</a>
    </div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Cook</h1>

<form action="" method="post" novalidate>
     {% csrf_token %} 
     {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Submit">
</form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends "base.html" %}
{% block content %} 
<h1>Cook list</h1>
{% if cook_list %}

<table class="table mt-5 table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Full name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Work experience</th>
            {% for cook in cook_list %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="{% url 'restaurant:cook-detail' cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a>
                
            </td>
            <td>
                {{ cook.username }}
       {% if user == cook %} <b>(Me)</b>{% endif%}

            </td>
            <td>
                {{ cook.email}}
            </td>
            <td>
                {{ cook.years_of_experience}} year{{ cook.years_of_experience | pluralize }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>There are no cooks</p>
{% endif %}
 <a href="{% url 'restaurant:cook-create' %}" class="card-link">Add new profile</a><br>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        {{ dish.name }}
        <a href="#" class="btn bg-gradient-danger my-auto float-end">
          Delete
        </a>
        <a href="{% url 'restaurant:dish-update' dish.id %}" class="btn btn-secondary my-auto float-end">
          Update
        </a>
      </h2>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3 text-dark">
        <p>
          <strong>Dish Type:</strong>
          <a class="text-gradient text-primary" href="{% url 'restaurant:dish-type-detail' pk=dish.dish_type.pk%}">{{ dish.dish_type }}</a>
        </p>
        <p><strong>Price:</strong> {{ dish.price }}</p>
      </div>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <h5>Description</h5>
        <p>{{ dish.description }}</p>
      </div>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <h5>
          Cooks who are responsible for preparing this dish
          {% if dish in user.dishes.all %}
          <form action="#" method="post">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-danger float-end my-auto">
              Delete me from this dish
            </button>
          </form>
          {% else %}
          <form action="#" method="post">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-success float-end my-auto">
              Assign me to this dish
            </button>
          </form>
          {% endif %}
        </h5>
      <ul>
        {% for cook in dish.cooks.all %}
          <li><a class="text-primary text-gradient" href="{% url 'restaurant:cook-detail' pk=cook.id%}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></li>
        {% empty %}
          <li>There are no cooks here.</li>
        {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/dish_form.html
{% extends 'base.html' %}
{% block content %}
<h2>Update dish</h2>
{% endblock %}

templates/restaurant/dish_list.html
{% extends 'base.html' %}
{% block content %}
<h1>All dishes</h1>
{% if dish_list %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Dish type</th>
            <th>Cook</th>
        </tr>
    </thead>
    <tbody>
        {% for dish in dish_list %}
        <tr>
            <td>
                <a href="{% url 'restaurant:dish-detail' dish.id %}">{{ dish.name }}</a>
            </td>
            <td>{{ dish.price}}</td>
            <td>{{ dish.dish_type }}</td>
            <td>{% for cook in dish.cooks.all %}{% if cook.first_name %}
                {{ cook.first_name }} {{ cook.last_name }} {% else %}{{ cook.username }}
                {% endif %}{% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>There are no dishes</p>
{% endif %}
<div class="make-dish">
<p >Make a new dish</p>
<a href="{% url 'restaurant:dish-create' %}">Nake</a>
</div>

{% endblock %}

templates/restaurant/dish_type_detail.html
{% extends "base.html" %}
{% block content %}
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ dish_type.name }}</h5>
    <p class="card-text">All dishes belonging to this dish type</p>
    {% for dish in dish_type.dish_set.all %}
    <b>
        <a href="{% url 'restaurant:dish-detail' dish.id %}">{{ dish.name }}</a>
    </b><br>
    
    {% empty %}
    <p>There are no dishes</p>
    {% endfor %}
    <a href="{% url 'restaurant:dish-type-update' dish_type.id %}" class="btn btn-primary">Update</a>
    <a href="#" class="btn btn-primary">Delete</a>
  </div>
</div>
{% endblock %}

templates/restaurant/dish_type_form.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Dish Type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock%}

templates/restaurant/dish_type_list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="make-dish">All Dish Types</h1>
{% if dish_type_list %}
<table class="table table-bordered table-hover shadow-lg bg-white mt-5">
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
        </tr>
    </thead>
    <tbody>
        {% for dish_type in dish_type_list %}
        <tr>
            <td>{{ dish_type.id }}</td>
            <td>
                <a href="{% url 'restaurant:dish-type-detail' dish_type.id %}">{{ dish_type.name }}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>There are no dish types </p>
{% endif %}
<div class="make-dish">
<p >Create a new dish type</p>
<a href="{% url 'restaurant:dish-type-create' %}" class="btn btn-secondary link-to-page btn-lg">Create</a>
</div>

{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Restaurant Kitchen Service Home</h1>
  <p>Welcome to Best Restaurant Ever!</p>

  <h2>Dynamic content</h2>
  <p>The restaurant kitchen service has the following record counts:</p>

  <ul>
    <li><strong>Cooks:</strong> {{ num_cooks }}</li>
    <li><strong>Dish Types:</strong> {{ num_dish_types }}</li>
    <li><strong>Dishes:</strong> {{ num_dishes }}</li>
  </ul>

  <p>You have visited this page
      {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}